[[CALCEPH]]
arch = "aarch64"
git-tree-sha1 = "d2729bec6c88ad49abe80a9e139132cc0647cef6"
os = "macos"

    [[CALCEPH.download]]
    sha256 = "8bd5c799fceb5d350d76ae7b28b3b49d0639594b0743bafae125c33e306b7f4d"
    url = "https://github.com/JuliaBinaryWrappers/CALCEPH_jll.jl/releases/download/CALCEPH-v3.5.5+0/CALCEPH.v3.5.5.aarch64-apple-darwin.tar.gz"
[[CALCEPH]]
arch = "aarch64"
git-tree-sha1 = "a3094e85b9484d2948f11acb98df55577b64e19f"
libc = "glibc"
os = "linux"

    [[CALCEPH.download]]
    sha256 = "804e8b40556d1d314da0dd6d44d3b9160e3bd583c668db63cdbac2dde8781cf9"
    url = "https://github.com/JuliaBinaryWrappers/CALCEPH_jll.jl/releases/download/CALCEPH-v3.5.5+0/CALCEPH.v3.5.5.aarch64-linux-gnu.tar.gz"
[[CALCEPH]]
arch = "aarch64"
git-tree-sha1 = "8623ab53bfcaeba361fc91d63cff96227cb269b9"
libc = "musl"
os = "linux"

    [[CALCEPH.download]]
    sha256 = "f6db361dd2a189489ad95d678b2c004444b3c49797421b3910e61f51becdf694"
    url = "https://github.com/JuliaBinaryWrappers/CALCEPH_jll.jl/releases/download/CALCEPH-v3.5.5+0/CALCEPH.v3.5.5.aarch64-linux-musl.tar.gz"
[[CALCEPH]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7205f49e3d6fe9486eaa6b43c08a20e26d74d199"
libc = "glibc"
os = "linux"

    [[CALCEPH.download]]
    sha256 = "6bfeb73ed2c550e525ad94ce788743c77219132559025ba60d53773be073adc1"
    url = "https://github.com/JuliaBinaryWrappers/CALCEPH_jll.jl/releases/download/CALCEPH-v3.5.5+0/CALCEPH.v3.5.5.armv6l-linux-gnueabihf.tar.gz"
[[CALCEPH]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "86c085d403fca2ee53dd01c6b0de56d176368abd"
libc = "musl"
os = "linux"

    [[CALCEPH.download]]
    sha256 = "fe2f08690f7c43481c221af89be85a37b5f972b53b8238d4de5561e698b79995"
    url = "https://github.com/JuliaBinaryWrappers/CALCEPH_jll.jl/releases/download/CALCEPH-v3.5.5+0/CALCEPH.v3.5.5.armv6l-linux-musleabihf.tar.gz"
[[CALCEPH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "351696ab796e4c065e411617c721b61e2e927847"
libc = "glibc"
os = "linux"

    [[CALCEPH.download]]
    sha256 = "4b6f1de4bf6694b8cd43f9786ae8d8f8bf39a00c9fa4583600ded45cee21fe60"
    url = "https://github.com/JuliaBinaryWrappers/CALCEPH_jll.jl/releases/download/CALCEPH-v3.5.5+0/CALCEPH.v3.5.5.armv7l-linux-gnueabihf.tar.gz"
[[CALCEPH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "541acfa803243d4eaf03597f3ee237c26895daa6"
libc = "musl"
os = "linux"

    [[CALCEPH.download]]
    sha256 = "05e6bc3e53d1236efe31446d1f4a6acec62374b464009f5124993e70febe1807"
    url = "https://github.com/JuliaBinaryWrappers/CALCEPH_jll.jl/releases/download/CALCEPH-v3.5.5+0/CALCEPH.v3.5.5.armv7l-linux-musleabihf.tar.gz"
[[CALCEPH]]
arch = "i686"
git-tree-sha1 = "4fcb11c9bc1e3770067237a065b07dfdb183d197"
libc = "glibc"
os = "linux"

    [[CALCEPH.download]]
    sha256 = "af3b8d858754a5d473c2485f3a7c40f34dad8779ad1e0bb4413bb7dce58533f2"
    url = "https://github.com/JuliaBinaryWrappers/CALCEPH_jll.jl/releases/download/CALCEPH-v3.5.5+0/CALCEPH.v3.5.5.i686-linux-gnu.tar.gz"
[[CALCEPH]]
arch = "i686"
git-tree-sha1 = "451a46a14fa23f7937f7580c1dfcea21e14d8c77"
libc = "musl"
os = "linux"

    [[CALCEPH.download]]
    sha256 = "875cff4dffa0b5f3e55605a0896d88796256f75ba8bc3dadc0b61f8df4c64eb8"
    url = "https://github.com/JuliaBinaryWrappers/CALCEPH_jll.jl/releases/download/CALCEPH-v3.5.5+0/CALCEPH.v3.5.5.i686-linux-musl.tar.gz"
[[CALCEPH]]
arch = "i686"
git-tree-sha1 = "2e954ff33b14926438ef9c634344f22964dbdca9"
os = "windows"

    [[CALCEPH.download]]
    sha256 = "b36a566621cd83e721f264381a1eee8c1ec7d341109e07031ec9513caf794b12"
    url = "https://github.com/JuliaBinaryWrappers/CALCEPH_jll.jl/releases/download/CALCEPH-v3.5.5+0/CALCEPH.v3.5.5.i686-w64-mingw32.tar.gz"
[[CALCEPH]]
arch = "powerpc64le"
git-tree-sha1 = "61b4fb4e3258c06e0a7f31b93973952a3ec6313a"
libc = "glibc"
os = "linux"

    [[CALCEPH.download]]
    sha256 = "ed1b7119c35635228bb4e4f1e35939c993df307be988d0577e1c3766132e761c"
    url = "https://github.com/JuliaBinaryWrappers/CALCEPH_jll.jl/releases/download/CALCEPH-v3.5.5+0/CALCEPH.v3.5.5.powerpc64le-linux-gnu.tar.gz"
[[CALCEPH]]
arch = "x86_64"
git-tree-sha1 = "9f9597d50b10b026c0c06087889a165ad5393e14"
os = "macos"

    [[CALCEPH.download]]
    sha256 = "586ca4825ac8efbde74cb2cc895d8df1813c12f40864df90cf3c71e62fdd1be5"
    url = "https://github.com/JuliaBinaryWrappers/CALCEPH_jll.jl/releases/download/CALCEPH-v3.5.5+0/CALCEPH.v3.5.5.x86_64-apple-darwin.tar.gz"
[[CALCEPH]]
arch = "x86_64"
git-tree-sha1 = "b74e432c0c8c81f01e75db62bd57baaa5e68cef3"
libc = "glibc"
os = "linux"

    [[CALCEPH.download]]
    sha256 = "8e0a71edc2eb9c851258501467887afd864c3fe43843f96a7c5cbbe83fc746f5"
    url = "https://github.com/JuliaBinaryWrappers/CALCEPH_jll.jl/releases/download/CALCEPH-v3.5.5+0/CALCEPH.v3.5.5.x86_64-linux-gnu.tar.gz"
[[CALCEPH]]
arch = "x86_64"
git-tree-sha1 = "be4cac2b247889d6d1036920d43fd7372c0c7f4e"
libc = "musl"
os = "linux"

    [[CALCEPH.download]]
    sha256 = "7e9cabf841c54e3795305af113a899abb0f07fbea99637dcebf596890d9b35dd"
    url = "https://github.com/JuliaBinaryWrappers/CALCEPH_jll.jl/releases/download/CALCEPH-v3.5.5+0/CALCEPH.v3.5.5.x86_64-linux-musl.tar.gz"
[[CALCEPH]]
arch = "x86_64"
git-tree-sha1 = "e0f4a326fa67e2847d61b4b39b09ebcd7d276053"
os = "freebsd"

    [[CALCEPH.download]]
    sha256 = "809a087ab85cb7dbc9d295da5922c990d78a8b51fe19d4a083dd8e2ab3130d58"
    url = "https://github.com/JuliaBinaryWrappers/CALCEPH_jll.jl/releases/download/CALCEPH-v3.5.5+0/CALCEPH.v3.5.5.x86_64-unknown-freebsd.tar.gz"
[[CALCEPH]]
arch = "x86_64"
git-tree-sha1 = "81739a590a964591c0a4aa3d270d28e22161aefa"
os = "windows"

    [[CALCEPH.download]]
    sha256 = "ab9ce6a8ccde9789486331485b22134a70c49497d917712d88247abdba68fdd3"
    url = "https://github.com/JuliaBinaryWrappers/CALCEPH_jll.jl/releases/download/CALCEPH-v3.5.5+0/CALCEPH.v3.5.5.x86_64-w64-mingw32.tar.gz"
