[[CALCEPH]]
arch = "aarch64"
git-tree-sha1 = "df47d6b5c71d81a8b1ce48b8e2d2eb16962dc278"
libc = "glibc"
os = "linux"

    [[CALCEPH.download]]
    sha256 = "151b28ee2554a07e96641399a100bbad44189d228d71a6cbc62868eb78da4db6"
    url = "https://github.com/JuliaBinaryWrappers/CALCEPH_jll.jl/releases/download/CALCEPH-v3.4.7+0/CALCEPH.v3.4.7.aarch64-linux-gnu.tar.gz"
[[CALCEPH]]
arch = "aarch64"
git-tree-sha1 = "77f87d86cfa8fe8687a84f8689dafcea9aeb8db9"
libc = "musl"
os = "linux"

    [[CALCEPH.download]]
    sha256 = "76443b5c12ace15d27fbaa746cae84269226643377bdc34c89d7a6c2c0007deb"
    url = "https://github.com/JuliaBinaryWrappers/CALCEPH_jll.jl/releases/download/CALCEPH-v3.4.7+0/CALCEPH.v3.4.7.aarch64-linux-musl.tar.gz"
[[CALCEPH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "45b6cf23f3b0615a1784b17ead6a34037eac770e"
libc = "glibc"
os = "linux"

    [[CALCEPH.download]]
    sha256 = "d1b09b78027cb1a2cffa055b92c3e03469269e21fa82ab0fdc1285d9e3d77b0d"
    url = "https://github.com/JuliaBinaryWrappers/CALCEPH_jll.jl/releases/download/CALCEPH-v3.4.7+0/CALCEPH.v3.4.7.armv7l-linux-gnueabihf.tar.gz"
[[CALCEPH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4101f1a8f7b8a1f628e92689349b30c73d025b3b"
libc = "musl"
os = "linux"

    [[CALCEPH.download]]
    sha256 = "f9d17d811a2c1d9a63a78a79c4c1b37821802fb50931f9bf73d5fc91a40aa091"
    url = "https://github.com/JuliaBinaryWrappers/CALCEPH_jll.jl/releases/download/CALCEPH-v3.4.7+0/CALCEPH.v3.4.7.armv7l-linux-musleabihf.tar.gz"
[[CALCEPH]]
arch = "i686"
git-tree-sha1 = "04b12b341991fb6aceb64e83bc12fd061c3292e5"
libc = "glibc"
os = "linux"

    [[CALCEPH.download]]
    sha256 = "b5cf1ad5211df60ad1668b5356648ff03ef0f2ff0acc8148b7c2c470da293b08"
    url = "https://github.com/JuliaBinaryWrappers/CALCEPH_jll.jl/releases/download/CALCEPH-v3.4.7+0/CALCEPH.v3.4.7.i686-linux-gnu.tar.gz"
[[CALCEPH]]
arch = "i686"
git-tree-sha1 = "bae8aa65200f653525626262bb1e6fd92fc13ba6"
libc = "musl"
os = "linux"

    [[CALCEPH.download]]
    sha256 = "677489847ade1fcbd3a8b487c6ccfef79bd9e07db6bdeb9cf7341926690098a9"
    url = "https://github.com/JuliaBinaryWrappers/CALCEPH_jll.jl/releases/download/CALCEPH-v3.4.7+0/CALCEPH.v3.4.7.i686-linux-musl.tar.gz"
[[CALCEPH]]
arch = "i686"
git-tree-sha1 = "68bda01eb916f5372238bf0772f7352c38e9b919"
os = "windows"

    [[CALCEPH.download]]
    sha256 = "1fb1a00efe3ffc0b33e869aba9573adb05b30b6f6a126b78135e5ee12ddc92e6"
    url = "https://github.com/JuliaBinaryWrappers/CALCEPH_jll.jl/releases/download/CALCEPH-v3.4.7+0/CALCEPH.v3.4.7.i686-w64-mingw32.tar.gz"
[[CALCEPH]]
arch = "powerpc64le"
git-tree-sha1 = "33b51a68f3ef249872634209939f75dcd2c55717"
libc = "glibc"
os = "linux"

    [[CALCEPH.download]]
    sha256 = "bc4a3758bdabd6b5a4a6982ba3c9e9519eb81b9bb6c8fdffa284cbbaccaead47"
    url = "https://github.com/JuliaBinaryWrappers/CALCEPH_jll.jl/releases/download/CALCEPH-v3.4.7+0/CALCEPH.v3.4.7.powerpc64le-linux-gnu.tar.gz"
[[CALCEPH]]
arch = "x86_64"
git-tree-sha1 = "ecc00c4b84fe33a46ed59235da3c89e42e59f205"
os = "macos"

    [[CALCEPH.download]]
    sha256 = "b6f1e11d0832dad76f6293d891838e9d8f4067152dd819cf2bda94abd5cbe640"
    url = "https://github.com/JuliaBinaryWrappers/CALCEPH_jll.jl/releases/download/CALCEPH-v3.4.7+0/CALCEPH.v3.4.7.x86_64-apple-darwin.tar.gz"
[[CALCEPH]]
arch = "x86_64"
git-tree-sha1 = "8ada842544e50468864038dee2c9b418bb494924"
libc = "glibc"
os = "linux"

    [[CALCEPH.download]]
    sha256 = "8b63eb8d2ee17eccc854d3e081fc315abb43d8b972ffc7d51a3d46d4ef8fbf11"
    url = "https://github.com/JuliaBinaryWrappers/CALCEPH_jll.jl/releases/download/CALCEPH-v3.4.7+0/CALCEPH.v3.4.7.x86_64-linux-gnu.tar.gz"
[[CALCEPH]]
arch = "x86_64"
git-tree-sha1 = "9ccfbe7d752f57515e36a5ecb041669e325989de"
libc = "musl"
os = "linux"

    [[CALCEPH.download]]
    sha256 = "59d4df0579aab91fa7994176bad67cf6ebf8475375bc936fd0b6659e3346c6b7"
    url = "https://github.com/JuliaBinaryWrappers/CALCEPH_jll.jl/releases/download/CALCEPH-v3.4.7+0/CALCEPH.v3.4.7.x86_64-linux-musl.tar.gz"
[[CALCEPH]]
arch = "x86_64"
git-tree-sha1 = "3d45ff6013730a18cabbc02ff13aa762c120c141"
os = "freebsd"

    [[CALCEPH.download]]
    sha256 = "a8daaf317d4a0c8c243824dc5684a5c1f173f9d397802c264e513b3541d6301c"
    url = "https://github.com/JuliaBinaryWrappers/CALCEPH_jll.jl/releases/download/CALCEPH-v3.4.7+0/CALCEPH.v3.4.7.x86_64-unknown-freebsd.tar.gz"
[[CALCEPH]]
arch = "x86_64"
git-tree-sha1 = "601c0bf0713cb96497b9107aaf3862a0b918493b"
os = "windows"

    [[CALCEPH.download]]
    sha256 = "0d451531d01a82425998d1245bd92a6cafe266da38169f009a606e3bd5c5eab1"
    url = "https://github.com/JuliaBinaryWrappers/CALCEPH_jll.jl/releases/download/CALCEPH-v3.4.7+0/CALCEPH.v3.4.7.x86_64-w64-mingw32.tar.gz"
