# Autogenerated wrapper script for CALCEPH_jll for x86_64-apple-darwin
export libcalceph

JLLWrappers.@generate_wrapper_header("CALCEPH")
JLLWrappers.@declare_library_product(libcalceph, "@rpath/libcalceph.1.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libcalceph,
        "lib/libcalceph.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
